[phases.setup]
nixPkgs = ["tesseract5"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
# Debug Step: Check if tesseract exists and what the PATH variable is
cmd = "which tesseract && echo '---' && echo $PATH"
